### ISSUE TITLE
splash screen

### ISSUE THREAD

**Issue by kakarimou** [mujehoxe/edu-app#15]
here's the gif
![phi_1](https://github.com/mujehoxe/edu-app/assets/12774292/507482b8-f9ed-4b52-b708-26c3f4418ec1)

for the background use the color #2196F3

**Comment by mujehoxe** [comment]
separating each element
[splash.zip](https://github.com/mujehoxe/edu-app/files/12432167/splash.zip)

**Comment by mujehoxe** [comment]
Might start loading content before the splash finishes
